
config:
  participant_data: ./give.zip
  global_info: ./README.md

tasks:
  - name: click
    flag: ctf{game_hack3d}
    build: ./click/compose.yml
    give:
      - ./click/give/index.html

  - name: its-a-base
    flag: ctf{hahahha_baseANYTHING_makes_brrrr}
    build: "./its_a_base/compose.yml"
    give:
      - "./its_a_base/give/message.txt"

  - name: oh-no-memory-limit
    flag: ctf{png_size_little_wrong}
    build: "./oh_no_memory_limit/compose.yml"
    give:
      - "./oh_no_memory_limit/give/secret.png.clip.png"

  - name: who
    flag: ctf{WHO_AM_I_im_zip_arch1ve_lol}
    build: ./who/compose.yml
    give:
      - ./who/give/confidential.zip

  - name: net-base64
    flag: ctf{base64_n0t_secur3}
    build: "./net_base64/compose.yml"
    give:
      - "./net_base64/give/PasswordChecker.exe"
